version: '3'
services:
  backend: 
    env_file:
      - docker/dev/backend-variables.env
    build:
      context: .
      dockerfile: docker/java.Dockerfile
    container_name: simple_spring_backend
    ports:
      - 8080:8080
      - 5005:5005
    restart: always

